# Generated by Django 4.2.22 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0123_ten_fold_product_defaults")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="issue_views_view",
            field=models.BooleanField(default=True),
        ),
    ]
