# Generated by Django 5.2

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0124_alter_project_issue_views_view")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="spreadsheet_view",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="SpreadsheetDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("grist_document_id", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("status", models.CharField(choices=[("provisioning", "Provisioning"), ("ready", "Ready"), ("degraded", "Degraded"), ("archiving", "Archiving"), ("archived", "Archived")], default="provisioning", max_length=16)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("grist_permissions", models.JSONField(default=dict)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("project", models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="project_%(class)s", to="db.project")),
                ("workspace", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="workspace_%(class)s", to="db.workspace")),
            ],
            options={"db_table": "spreadsheet_documents"},
        ),
        migrations.CreateModel(
            name="SpreadsheetOperation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("kind", models.CharField(choices=[("provision", "Provision"), ("rename", "Rename"), ("duplicate", "Duplicate"), ("reconcile_access", "Reconcile access"), ("archive", "Archive")], max_length=24)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("complete", "Complete"), ("failed", "Failed")], default="pending", max_length=16)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("available_at", models.DateTimeField(auto_now_add=True)),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("spreadsheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="operations", to="db.spreadsheetdocument")),
            ],
            options={"db_table": "spreadsheet_operations"},
        ),
        migrations.CreateModel(
            name="SpreadsheetFormPublication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("view_section_id", models.PositiveIntegerField()),
                ("share_key", models.CharField(max_length=255)),
                ("access", models.CharField(choices=[("public", "Public"), ("authenticated", "Authenticated")], default="public", max_length=16)),
                ("enabled", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("spreadsheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="form_publications", to="db.spreadsheetdocument")),
            ],
            options={"db_table": "spreadsheet_form_publications"},
        ),
        migrations.CreateModel(
            name="SpreadsheetAgentExecution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                ("id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ("operation", models.CharField(max_length=32)),
                ("payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("running", "Running"), ("complete", "Complete"), ("uncertain", "Uncertain")], default="pending", max_length=16)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("result", models.JSONField(null=True)),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_created_by", to=settings.AUTH_USER_MODEL, verbose_name="Created By")),
                ("updated_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="%(class)s_updated_by", to=settings.AUTH_USER_MODEL, verbose_name="Last Modified By")),
                ("spreadsheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="agent_executions", to="db.spreadsheetdocument")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={"db_table": "spreadsheet_agent_executions"},
        ),
        migrations.AddConstraint(model_name="spreadsheetdocument", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("project", "name"), name="spreadsheet_unique_active_project_name")),
        migrations.AddConstraint(model_name="spreadsheetformpublication", constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("spreadsheet", "view_section_id"), name="spreadsheet_unique_active_form_section")),
        migrations.AddConstraint(model_name="spreadsheetagentexecution", constraint=models.UniqueConstraint(fields=("spreadsheet", "user", "idempotency_key"), name="spreadsheet_unique_agent_execution")),
    ]
