# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0125_spreadsheets")]

    operations = [
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="document_type",
            field=models.CharField(
                choices=[("sheet", "Sheet"), ("form", "Form")], default="sheet", max_length=8
            ),
        ),
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="grist_form_view_section_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
