# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0126_spreadsheet_document_types")]

    operations = [
        migrations.AddField(
            model_name="spreadsheetdocument",
            name="grist_form_view_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
