# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("db", "0127_spreadsheet_form_view_id")]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="is_tour_completed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_navigation_tour_completed",
            field=models.BooleanField(default=True),
        ),
    ]
