# Generated by Django 5.2.15 on 2026-09-20

from django.db import migrations


def reset_personal_sidebar_pins(apps, schema_editor):
    WorkspaceUserPreference = apps.get_model("db", "WorkspaceUserPreference")
    WorkspaceUserPreference.objects.filter(
        key__in=["drafts", "your_work", "stickies"],
        deleted_at__isnull=True,
    ).update(is_pinned=False)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0128_disable_first_time_tours"),
    ]

    operations = [
        migrations.RunPython(reset_personal_sidebar_pins, noop_reverse),
    ]
